### PR TITLE
Strip carriage return from bash scripts

### PR DESCRIPTION
**Pull request by krajla**
## What's the problem
There are issues running bash scripts on Linux with Windows style EOL. 

Encountered issues after deploying from Windows.

## What is being changed
Running a `sed  -i 's/\r//' <file>` command to remove any carriage return after adding a file to the EC2 image.

### CODE REVIEW

**Comment by 314pies** [comment]
Hi [krajla](https://github.com/krajla),
Thanks for noticing this issue.  
We have also noticed that windows EOF chars will cause bash script failed to execute sometime, the way we solve it at that time is to pack it as a release.zip and have people download it instead of clone it.  
But as many custom use case will involve in making change to the bash script (ex: `start_server.sh`), it probably make more sense not to address this in our side.

**Comment by 314pies** [comment]
The only comment I have is that there seems to have some duplicate code (for deploying bash script, grant it execution permission and run `sed` command to pre-process it) - it will be nice if we can pack it as a function and re-use it.  
I will do that in a follow up PR though.

**Comment by 314pies** [comment]
PR merged.    
Thanks, [krajla](https://github.com/krajla) :) !

**Comment by 314pies** [comment]
Follow-up PR:  
https://github.com/VeriorPies/MineCloud/pull/52

**Comment by krajla** [comment]
> The only comment I have is that there seems to have some duplicate code (for deploying bash script ...

Adding to this, if the scope of the project does increase it might become increasingly harder to maintain multiple bash scripts. 

It might be worth looking into either:
 - A dedicated mini CLI app(statically typed or not depending on the preference of the contributors 😄).
 - A small app that listens to SNS messages published by the Lambda functions (instead of SSM), with the added bonus of specific topic handling in case of multiple/different types of deployments.
 
 Just my 2 cents.

**Pull request merged**
